### ISSUE TITLE
是否开放自行训练鸽手？

### ISSUE THREAD

**Issue by iamPorter** [aqtq314/Vogen.Client#3]
如题，请问是否可以自行创建声库？如果可以，创建工具是什么？
此外，我注意到你的用户仓库下有[VogenSVS](https://github.com/aqtq314/VogenSVS)一项。请问是声库创建平台吗？

**Comment by aqtq314** [comment]
目前是申请制，qq联系申请。由于sovits的前车之鉴，这边仍在评估是否开放声库训练。VogenSVS原计划是重制后的编辑器代码仓，但三次元事情太多了导致这边一直在咕咕咕，目前进度略高于新建文件夹。。。
